<?php

/**
 * @file
 * A demo for the D2D Search module.
 */

require_once 'includes/d2dsearch_demo.form.inc';
require_once 'includes/d2dsearch_demo.news.inc';

/**
 * Implements hook_menu_alter().
 */
function d2dsearch_demo_menu_alter(&$items) {
  $items['admin/d2d/search/demo'] = array(
    'title' => 'D2D Search Demo',
    'page callback' => 'd2dsearch_demo_main',
    'access arguments' => array('administer d2dsearch demo'),
    'type' => MENU_LOCAL_TASK,
    'weight' => 80,
  );
  $items['admin/d2d/search/demo/news/get_result'] = array(
    'page callback' => 'd2dsearch_demo_get_results',
    'access arguments' => array('administer d2dsearch demo'),
    'type' => MENU_CALLBACK,
  );
  return $items;
}

/**
 * Implements hook_permission().
 */ 
function d2dsearch_demo_permission() {
  return array(
    'administer d2dsearch demo' => array(
      'title' => t('administer D2D Search Demo'),
    ),
  );
}

/**
 * Implements hook_d2dsearch_query_type().
 */
function d2dsearch_demo_d2dsearch_query_type() {
  $types = array();
  $types['d2dsearch_demo_news'] = array(
    'callback' => '_d2dsearch_demo_news_callback',
  );
  return $types;
}
